[project]
name = "engage"
version = "0.0.1"

[build-system]
requires = ["poetry==1.4.2"]

[tool.poetry]
name = "engage"
version = "0.0.1"
description = "City Council Engage-O-Tron"
authors = ["Dave Peck <davepeck@davepeck.org>"]

[tool.black]
target-version = ["py311"]

[tool.isort]
known_first_party = "city"
profile = "black"

[tool.pyright]
include = ["city"]
typeCheckingMode = "basic"
useLibraryCodeForTypes = true

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.133"
django = "^4.2"
requests = "^2.28.2"
beautifulsoup4 = "^4.12.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
ruff = "^0.0.261"
