# Generated by Django 4.2 on 2023-04-16 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legistar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('summary', models.TextField(help_text='The summary of the meeting.')),
                ('extra', models.JSONField(db_index=True, default=dict, help_text='Extra data.')),
                ('meeting', models.ForeignKey(help_text='The summarized meeting.', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='legistar.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Summary',
                'verbose_name_plural': 'Meeting Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegislationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('summary', models.TextField(help_text='The summary of the legislation.')),
                ('extra', models.JSONField(db_index=True, default=dict, help_text='Extra data.')),
                ('legislation', models.ForeignKey(help_text='The legislation that the summary is for.', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='legistar.legislation')),
            ],
            options={
                'verbose_name': 'Legislation Summary',
                'verbose_name_plural': 'Legislation Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
