name: "Run All Tests"

on: push

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the `engage` repository
        uses: actions/checkout@v4
      - name: Install node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install python 3.12.x
        uses: actions/setup-python@v5
        id: install-python
        with:
          python-version: "3.12.2"
      - name: Install node dependencies
        run: npm install
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Check python formatting (ruff format)
        run: ruff format --check server
      - name: Check python linting (ruff)
        run: ruff check server
      - name: Check python types (pyright)
        run: npx pyright
      - name: Run python tests
        run: python manage.py test
        env:
          BASE_URL: http://localhost:3000
          DEBUG: NO
          SECURE_SSL_REDIRECT: NO
          SECRET_KEY: supersecret
          EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
