# Generated by Django 4.2.1 on 2023-05-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The original URL where the document was found.",
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        db_index=True, help_text="The kind of document.", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the document.", max_length=255
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="The MIME type of the document.", max_length=255
                    ),
                ),
                (
                    "raw_content",
                    models.BinaryField(
                        blank=True,
                        default=None,
                        help_text="If the content was obtained via means other than the URL, \n(for instance, was obtained by grabbing a piece of the HTML content at the URL)\n, then this field contains the raw text of the document.",
                        null=True,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The extracted full text of the document. Since extraction\n        happens asynchronously, this field may be empty until the extraction\n        process has completed.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("body", models.TextField(help_text="A detailed summary of a text.")),
                ("headline", models.TextField(help_text="A brief summary of a text.")),
                (
                    "original_text",
                    models.TextField(help_text="The original summarized text."),
                ),
                (
                    "chunks",
                    models.JSONField(
                        default=list,
                        help_text="Text chunks sent to the LLM for summarization.",
                    ),
                ),
                (
                    "chunk_summaries",
                    models.JSONField(
                        default=list, help_text="LLM outputs for each text chunk."
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        db_index=True,
                        help_text="The SummarizationStyle used to generate this summary.",
                        max_length=255,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The summarized document.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document summary",
                "verbose_name_plural": "Document summaries",
            },
        ),
        migrations.AddConstraint(
            model_name="documentsummary",
            constraint=models.UniqueConstraint(
                fields=("document", "style"), name="unique_document_summary_for_style"
            ),
        ),
    ]
