# Generated by Django 4.2 on 2023-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The original URL where the document was found.', unique=True)),
                ('kind', models.CharField(db_index=True, help_text='The kind of document.', max_length=255)),
                ('title', models.CharField(help_text='The title of the document.', max_length=255)),
                ('mime_type', models.CharField(help_text='The MIME type of the document.', max_length=255)),
                ('file', models.FileField(help_text='The downloaded document.', upload_to='documents')),
            ],
        ),
    ]
