# Generated by Django 4.2 on 2023-04-13 18:58

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this document was scraped.')),
                ('source_url', models.URLField(help_text='The original URL where the document was found.')),
                ('event_date', models.DateField(blank=True, db_index=True, help_text='The date of the event the document is about, if relevant.', null=True)),
                ('kind', models.CharField(choices=[('Agenda', 'Agenda'), ('Agenda Packet', 'Agenda Packet'), ('Ord Summary', 'Ordinance Summary'), ('Transcript', 'Transcript'), ('Appt', 'Appointment'), ('CF', 'Clerk File'), ('CB', 'Council Bill'), ('CBA', 'Council Budget Action'), ('Inf', 'Information Item'), ('IRC', 'Introduction and Referral Calendar'), ('Min', 'Minutes'), ('Ord', 'Ordinance'), ('Res', 'Resolution'), ('SLI', 'Statement of Legislative Intent')], db_index=True, help_text='The kind of document.', max_length=100)),
                ('file', models.FileField(blank=True, default=None, help_text='The downloaded document, if any.', null=True, upload_to='documents')),
                ('text', models.TextField(blank=True, help_text='The extracted text of the document.')),
                ('embedding', pgvector.django.VectorField(blank=True, default=None, null=True, verbose_name=1536)),
            ],
        ),
    ]
