# Generated by Django 4.2 on 2023-04-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extractor', models.CharField(help_text='Description of the extractor used.', max_length=255)),
                ('text', models.TextField(help_text='The text content of the document.')),
                ('document', models.ForeignKey(help_text='The document this text belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='documents.document')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttext',
            constraint=models.UniqueConstraint(fields=('document', 'extractor'), name='unique_document_text'),
        ),
    ]
